mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls'))
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
  # ex: /polls/
  path('', views.IndexView.as_view(), name="index"),
  # ex: /polls/new
  path('create/', views.add_question, name="create"),
  #ex: polls/5/
  path('<int:pk>/', views.DetailView.as_view(), name='detail'),
  # ex: /polls/5/results/
  path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
  # ex: /polls/5/delete/
  path('<int:pk>/delete/', views.DeleteView.as_view(), name='delete'),
  # ex: /polls/5/vote/
  path('<int:question_id>/vote/', views.vote, name='vote')
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
  question_text = models.CharField(max_length=200)
  pub_date = models.DateTimeField("date published")
  def __str__(self):
    return self.question_text
  def was_published_recently(self):
    return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
  question = models.ForeignKey(Question, on_delete=models.CASCADE)
  choice_text = models.CharField(max_length=200)
  votes = models.IntegerField(default=0)
  def __str__(self):
    return self.choice_text

polls/forms.py
from django import forms

from .models import Question, Choice

class QuestionForm(forms.ModelForm):
  class Meta:
    model = Question
    fields = [
      'question_text',
      'pub_date'
    ]

polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.contrib import messages
from .forms import QuestionForm

from extra_views import CreateWithInlinesView, UpdateWithInlinesView, InlineFormSetFactory

from .models import Question, Choice

class IndexView(generic.ListView):
  template_name = 'polls/index.html'
  context_object_name = 'latest_question_list'

  def get_queryset(self):
    """Return the last five published questions."""
    return Question.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
  model = Question
  template_name = 'polls/detail.html'

class ResultsView(generic.DetailView):
  model = Question
  template_name = 'polls/results.html'

class DeleteView(generic.DeleteView):
  model = Question
  template_name = 'polls/delete.html'  
  success_url = reverse_lazy('polls:index')


def add_question(request):
  if request.method == 'POST':
   
    choices = []
    choice1 = request.POST.get('choice1')
    choice2 = request.POST.get('choice2')
    choice3 = request.POST.get('choice3')
    choice4 = request.POST.get('choice4')
    if (choice1):
      choices.append(choice1)
    if (choice2):
      choices.append(choice2)
    if (choice3):
      choices.append(choice3)
    if (choice4):
      choices.append(choice4)

    question_form = QuestionForm(request.POST, instance=Question())

    if question_form.is_valid():
      new_question = question_form.save()
      print(new_question.id)
      for c in choices:
        Choice.objects.create(choice_text=c, question=new_question)
      return HttpResponseRedirect('/polls/')

  else:
    question_form = QuestionForm(request.POST, instance=Question())
    return render(request, 'polls/create.html', {'q_form': question_form})
    


def vote(request, question_id):
  question = get_object_or_404(Question, pk=question_id)
  try:
    selected_choice = question.choice_set.get(pk=request.POST['choice'])
  except (KeyError, Choice.DoesNotExist):
    # in this case redisplay the question voting form
    return render(request, 'polls/detail.html', {
      'question': question,
      'error_message': "You didn't select a choice",
    })
  else:
    selected_choice.votes += 1
    selected_choice.save()
    # Always return HttpResponseRedirect after successfully handling POST data.
    # This prevents data from being posted twice if user hits back button
    return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

polls/templates/polls/base.html
<!doctype html>
<html>
  <head>
    <title>Polls</title>
  </head>
  <body>
    <h1>The Polls!</h1>
    <a href="{% url 'polls:index' %}">Home</a>
    {% block content %} {% endblock %}
  </body>
</html>

polls/templates/polls/create.html
{% extends 'polls/base.html' %}
{% block content %}
<h1>New Question</h1>

<form action="" method="POST">
  {% csrf_token %} {% for field in q_form %} 
    {{ field.label_tag }} {{ field }} 
  {% endfor %}<br>

  Choice: <input type="text" name="choice1" id="">
  Choice: <input type="text" name="choice2" id="">
  Choice:<input type="text" name="choice3" id="">
  Choice:<input type="text" name="choice4" id="">
  
   <input type="submit" value="Create Question" />
    <a href="{% url 'polls:index' %}">Cancel</a>

</form> 
{% endblock %}

polls/templates/polls/delete.html
{% extends 'polls/base.html' %}
{% block content %}

<form method="post">
  {% csrf_token %}
  <h2>Are you sure you want to delete the question '{{ question.question_text }}'?</h2>
  <p>
    Along with deleting the question, you will also be deleting:
    <ul>
    
     {% for choice in question.choice_set.all %}

    <li>{{ choice.votes }} vote{{choice.votes|pluralize}} for '{{ choice.choice_text }}'</li>
    

  {% endfor %} 
  </ul>
  </p>
  <input type="submit" value="Yes" />
  <a href="{% url 'polls:index' %}">Cancel</a>
</form>


{% endblock %}

polls/templates/polls/detail.html
{% extends 'polls/base.html' %}
  {% block content %}
<h1>{{ question.question_text }}</h1>

{% if error_message %}
<p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
  {% csrf_token %} {% for choice in question.choice_set.all %}
  <input
    type="radio"
    name="choice"
    id="choice{{ forloop.counter }}"
    value="{{choice.id}}"
  />
  <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label
  ><br />
  {% endfor %}
  <input type="submit" value="Vote" />
</form>
{% endblock %}

polls/templates/polls/index.html
{% extends 'polls/base.html' %}
{% block content %}
{% if messages %}
  {% for message in messages %}
    {{ message }}
  {% endfor %}
{% endif %}

{% if latest_question_list %}
<ul>
  {% for question in latest_question_list %}
  <li>
    <a href="{% url 'polls:detail' question.id %}"
      >{{question.question_text}}</a
    >
    <a href="{% url 'polls:delete' question.id %}">Delete</a>
  </li>
  {% endfor %}
</ul>
{% else %}
<p>No polls are available.</p>
{% endif %}
<a href="{% url 'polls:create'  %}">Add a new question</a>
{% endblock %}

polls/templates/polls/results.html
{% extends 'polls/base.html' %}
{% block content %}
<h1>{{ question.question_text }}</h1>

<ul>
  {% for choice in question.choice_set.all %}
  <li>
    {{ choice.choice_text }} -- {{ choice.votes }}
    vote{{choice.votes|pluralize}}
  </li>
  {% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
{% endblock %}